logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{Request-Id}] - %msg%n"

spring:
  application:
    name: SpeakSmart
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  #  main:
  #    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          speaksmart:
            jwt-secret: ${JWT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
          linkedin:
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_CLIENT_SECRET}
            redirect-uri: ${LINKEDIN_REDIRECT_URI}
            scope: openid,profile,email
            provider: linkedin
            authorization-grant-type: authorization_code

        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
            user-name-attribute: email

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
        default_schema: public
        format_sql: false
    open-in-view: false

#  data:
#    mongodb:
#      uri: ${MONGODB_URI}
#      database: ${MONGODB_NAME}

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

cors:
  allowed-origins: ${ALLOWED_ORIGINS}
groq:
  api:
    key: ${GROQ_API_KEY}

supabase:
  url: ${SUPABASE_URL}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
  storage:
    buckets:
      user: ${SUPABASE_USER_BUCKET}
      public: ${SUPABASE_PUBLIC_BUCKET}
      temp: ${SUPABASE_TEMP_BUCKET}